name: Lab1

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15

      - name: Download ninjs
        run: sudo apt install ninja-build

      - name: Create my bood
        run: go build ./build/cmd/bood

      - name: Test tested-binary
        run: cd ./build && ../bood

      - name: Test example
        run: |
          cd ./example && ../bood